### PR TITLE
Fix CI for Ruby 2.4

### PR DESCRIPTION
**Pull request by Morriar**
Use singleton method for `Pathname::glob` as the instance one is not defined in Ruby 2.4.

Signed-off-by: Alexandre Terrasa <alexandre.terrasa@shopify.com>

### CODE REVIEW

**Comment by rafaelfranca** [comment]
@Morriar did you see https://github.com/Shopify/tapioca/pull/13?

**Comment by Morriar** [comment]
> @Morriar did you see #13?

Urghf... Apparently I was not watching this repo...

**Comment by rafaelfranca** [comment]
Can we close this PR now?

**Comment by Morriar** [comment]
Superseded by #13.

**Pull request closed without merging**
