### PR TITLE
Support Postgres Interval, Range, Bit, and BitVarying

### PR DESCRIPTION
**Pull request by alex-tan**
### Motivation

Adds support for this column type.

### Implementation

I followed the other implementations of the postgres column types.

### Tests

No tests since there's not an established way of doing that in the repo for this type of feature.

### CODE REVIEW

**Review by amomchilov — APPROVED** [review]
Thanks!

Are there any other PG column types that we should add here?

**Comment by alex-tan** [comment]
I tested these three new columns however [`ActiveRecord::Point`](https://github.com/rails/rails/blob/6b3c4781b31953884371a3bbd7a4aa06457762f7/activerecord/lib/active_record/connection_adapters/postgresql/oid/point.rb#L4) doesn't resolve after the rbis are generated. Is there a place I should add a shim for that?

**Comment by amomchilov** [comment]
@alex-tan It seems to fall under this category, so perhaps you can just declare it in `activerecord_postgresql.rbi` as well?

https://github.com/Shopify/tapioca/blob/28b06aac4f9c97783bb5c23512ae09d50cec45b9/sorbet/rbi/shims/activerecord_postgresql.rbi#L3

```ruby
class Point < Struct.new(:x, :y)
   sig { returns(FloatButImNotSure) } # TODO: Fill in correct types
   def x; end
   
   sig { params(x:FloatButImNotSure).returns(FloatButImNotSure) }
   def x=(x); end
   
   sig { returns(FloatButImNotSure) }
   def y; end

   sig { params(x:FloatButImNotSure).returns(FloatButImNotSure) }
   def y=(x); end
end
```

**Comment by amomchilov** [comment]
Ahh, you're right, these are just shims for Tapioca's own internal use.

Hmmm... I'll ask for guidance internally. To get you unblocked quicker, would you like to roll this PR back to just the original support for `Interval`? I'll approve/merge that right away, then you can split the rest in their own new PR

**Comment by alex-tan** [comment]
Sounds good, thanks 👍

**Review by amomchilov — APPROVED** [review]

**Comment by alex-tan** [comment]
@egiurleo sure thing, done 👍

**Pull request merged**
