### PR TITLE
Recommend `bundle exec`

### PR DESCRIPTION
**Pull request by ghiculescu**
I dunno about you guys, but I always forget this.

### CODE REVIEW

**Comment by ghiculescu** [comment]
Oh, I didn't know that. By binstubs do you mean we should be encouraging something `bin/rails tapioca generate ...` ? @rafaelfranca

**Comment by rafaelfranca** [comment]
I mean this https://bundler.io/man/bundle-binstubs.1.html. The `bin/rails` is a binstub but every gem you have in your project you should have a binstub.

**Comment by ghiculescu** [comment]
wow, i just ran `bundle install --binstubs` and it generated a whole bunch. game changer.

**Comment by ghiculescu** [comment]
Do you know if anyone is thinking about making that the default `bundle install` behaviour?

**Comment by rafaelfranca** [comment]
I think it was at some point but it broke a few things. I "think" bundler 3 would make it the default again but "citation needed".

**Comment by Morriar** [comment]
Should we also remove the `bundle exec` we use in the [README](https://github.com/Shopify/tapioca/blob/master/README.md#installation) then?

**Pull request closed without merging**
